// Created by iWeb 3.0.4 local-build-20140509

setTransparentGifURL('Media/transparent.gif');function applyEffects()
{var registry=IWCreateEffectRegistry();registry.registerEffects({shadow_0:new IWShadow({blurRadius:10,offset:new IWPoint(4.2426,4.2426),color:'#000000',opacity:0.750000}),shadow_2:new IWShadow({blurRadius:10,offset:new IWPoint(4.2426,4.2426),color:'#000000',opacity:0.750000}),stroke_1:new IWStrokeParts([{rect:new IWRect(-1,1,2,76),url:'Pretty_Good_Notary_files/stroke_8.png'},{rect:new IWRect(-1,-1,2,2),url:'Pretty_Good_Notary_files/stroke_9.png'},{rect:new IWRect(1,-1,253,2),url:'Pretty_Good_Notary_files/stroke_10.png'},{rect:new IWRect(254,-1,2,2),url:'Pretty_Good_Notary_files/stroke_11.png'},{rect:new IWRect(254,1,2,76),url:'Pretty_Good_Notary_files/stroke_12.png'},{rect:new IWRect(254,77,2,2),url:'Pretty_Good_Notary_files/stroke_13.png'},{rect:new IWRect(1,77,253,2),url:'Pretty_Good_Notary_files/stroke_14.png'},{rect:new IWRect(-1,77,2,2),url:'Pretty_Good_Notary_files/stroke_15.png'}],new IWSize(255,78)),stroke_0:new IWStrokeParts([{rect:new IWRect(-1,1,2,76),url:'Pretty_Good_Notary_files/stroke.png'},{rect:new IWRect(-1,-1,2,2),url:'Pretty_Good_Notary_files/stroke_1.png'},{rect:new IWRect(1,-1,253,2),url:'Pretty_Good_Notary_files/stroke_2.png'},{rect:new IWRect(254,-1,2,2),url:'Pretty_Good_Notary_files/stroke_3.png'},{rect:new IWRect(254,1,2,76),url:'Pretty_Good_Notary_files/stroke_4.png'},{rect:new IWRect(254,77,2,2),url:'Pretty_Good_Notary_files/stroke_5.png'},{rect:new IWRect(1,77,253,2),url:'Pretty_Good_Notary_files/stroke_6.png'},{rect:new IWRect(-1,77,2,2),url:'Pretty_Good_Notary_files/stroke_7.png'}],new IWSize(255,78)),stroke_3:new IWEmptyStroke(),shadow_1:new IWShadow({blurRadius:10,offset:new IWPoint(4.2426,4.2426),color:'#000000',opacity:0.750000}),stroke_2:new IWStrokeParts([{rect:new IWRect(-1,1,2,76),url:'Pretty_Good_Notary_files/stroke_16.png'},{rect:new IWRect(-1,-1,2,2),url:'Pretty_Good_Notary_files/stroke_17.png'},{rect:new IWRect(1,-1,253,2),url:'Pretty_Good_Notary_files/stroke_18.png'},{rect:new IWRect(254,-1,2,2),url:'Pretty_Good_Notary_files/stroke_19.png'},{rect:new IWRect(254,1,2,76),url:'Pretty_Good_Notary_files/stroke_20.png'},{rect:new IWRect(254,77,2,2),url:'Pretty_Good_Notary_files/stroke_21.png'},{rect:new IWRect(1,77,253,2),url:'Pretty_Good_Notary_files/stroke_22.png'},{rect:new IWRect(-1,77,2,2),url:'Pretty_Good_Notary_files/stroke_23.png'}],new IWSize(255,78))});registry.applyEffects();}
function hostedOnDM()
{return false;}
function onPageLoad()
{loadMozillaCSS('Pretty_Good_Notary_files/Pretty_Good_NotaryMoz.css')
adjustLineHeightIfTooBig('id1');adjustFontSizeIfTooBig('id1');adjustLineHeightIfTooBig('id2');adjustFontSizeIfTooBig('id2');adjustLineHeightIfTooBig('id3');adjustFontSizeIfTooBig('id3');adjustLineHeightIfTooBig('id4');adjustFontSizeIfTooBig('id4');adjustLineHeightIfTooBig('id5');adjustFontSizeIfTooBig('id5');adjustLineHeightIfTooBig('id6');adjustFontSizeIfTooBig('id6');adjustLineHeightIfTooBig('id7');adjustFontSizeIfTooBig('id7');adjustLineHeightIfTooBig('id8');adjustFontSizeIfTooBig('id8');adjustLineHeightIfTooBig('id9');adjustFontSizeIfTooBig('id9');adjustLineHeightIfTooBig('id10');adjustFontSizeIfTooBig('id10');adjustLineHeightIfTooBig('id11');adjustFontSizeIfTooBig('id11');adjustLineHeightIfTooBig('id12');adjustFontSizeIfTooBig('id12');adjustLineHeightIfTooBig('id13');adjustFontSizeIfTooBig('id13');adjustLineHeightIfTooBig('id14');adjustFontSizeIfTooBig('id14');adjustLineHeightIfTooBig('id15');adjustFontSizeIfTooBig('id15');adjustLineHeightIfTooBig('id16');adjustFontSizeIfTooBig('id16');adjustLineHeightIfTooBig('id18');adjustFontSizeIfTooBig('id18');fixAllIEPNGs('Media/transparent.gif');fixupIECSS3Opacity('id17');applyEffects()}
